services:
  postgres:
    image: postgres:16
    container_name: kafucka-postgres
    environment:
      POSTGRES_USER: <POSTGRES_USER>
      POSTGRES_PASSWORD: <POSTGRES_PWD>
      POSTGRES_DB: <POSTGRES_DB_NAME>
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U <POSTGRES_USER> -d <POSTGRES_DB_NAME>"]
      interval: 5s
      timeout: 5s
      retries: 20

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafucka-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://<TAILSCALE_IP>:9092"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 12

  auth-api:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: kafucka-auth-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://<POSTGRES_USER>:<POSTGRES_PWD>@postgres:5432/<POSTGRES_DB_NAME>
      KAFKA_SERVER_URL: kafka:29092
      SECRET: your_secret_here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"

  ingestion-api:
    build:
      context: .
      dockerfile: Dockerfile.ingestion
    container_name: kafucka-ingestion-api
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://<POSTGRES_USER>:<POSTGRES_PWD>@postgres:5432/<POSTGRES_DB_NAME>
      KAFKA_SERVER_URL: kafka:29092
      SECRET: your_secret_here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8001:8000"

volumes:
  postgres_data:
  kafka_data:
